#!/usr/bin/env python

import argparse
import sys
import pycNic

sys.setrecursionlimit(20000)


parser = argparse.ArgumentParser()
parser.add_argument("fileLog", default="", nargs="?",
                    help="file is the filename of the log")

parser.add_argument("--c", help="create the quiz",
                    action="store_true")


#################################################
#                        MAIN                   #
#################################################
if __name__ == '__main__':
    pass