#!/usr/bin/env python

import argparse
import sys
from core import pycNic

sys.setrecursionlimit(20000)


parser = argparse.ArgumentParser()
parser.add_argument("fileCfg", help="Filename of the cfg file")

#################################################
#                        MAIN                   #
#################################################
if __name__ == '__main__':
    args = parser.parse_args()
    fileCfg = args.fileCfg
    pycNic.run(fileCfg)